In [11]:
#Question 1
name = "S Bhaskar Nikhil"
age = 20

print("Name - ", name)
print("Age - ", age)

Name -  S Bhaskar Nikhil
Age -  20


In [12]:
#Question 2
X= "Datascience is used to extact meaningful insights."
X.split()

['Datascience', 'is', 'used', 'to', 'extact', 'meaningful', 'insights.']

In [13]:
#Question 3
def mul(a,b):
  res = a*b
  return res

a = int(input("Enter number 1 - "))
b = int(input("Enter number 2 - "))
print("Multiplication of a and b yields - ",mul(a,b))

Enter number 1 - 6
Enter number 2 - 7
Multiplication of a and b yields -  42


In [14]:
#Question 4
capitals = {
    'Maharashtra': 'Mumbai',
    'Tamil Nadu': 'Chennai',
    'Telangana':'Hyderabad',
    'Karnataka': 'Bangalore',
    'Andhra Pradesh': 'Amaravati'
}

for state, capital in capitals.items():
    print("State:", state)
    print("Capital:", capital)
    print("----------")

print("Keys:", list(capitals.keys()))
print("Values:", list(capitals.values()))

State: Maharashtra
Capital: Mumbai
----------
State: Tamil Nadu
Capital: Chennai
----------
State: Telangana
Capital: Hyderabad
----------
State: Karnataka
Capital: Bangalore
----------
State: Andhra Pradesh
Capital: Amaravati
----------
Keys: ['Maharashtra', 'Tamil Nadu', 'Telangana', 'Karnataka', 'Andhra Pradesh']
Values: ['Mumbai', 'Chennai', 'Hyderabad', 'Bangalore', 'Amaravati']


In [15]:
#Question 5
num = list(range(1, 1001))
print(num)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [16]:
#Question 6
import numpy as np
np.identity(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [17]:
#Question 7
import random as rand
matrix = [[rand.randint(1, 9) for _ in range(3)] for _ in range(3)]
print(matrix)

[[6, 4, 5], [3, 3, 6], [5, 2, 4]]


In [18]:
#Question 8
mat1 = np.array([[rand.randint(1, 20) for _ in range(3)] for _ in range(3)])
mat2 = np.array([[rand.randint(1, 20) for _ in range(3)] for _ in range(3)])
res = mat1 + mat2
print("matrix 1 - \n", mat1)
print("\nmatrix 2 - \n", mat2)
print("\nres = \n", res)

matrix 1 - 
 [[17 14  2]
 [14  5  3]
 [12 20  2]]

matrix 2 - 
 [[ 1 10  8]
 [16  1  4]
 [19 13 15]]

res = 
 [[18 24 10]
 [30  6  7]
 [31 33 17]]


In [19]:
#Question 9
from datetime import datetime, timedelta

start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)
dates = []
current_date = start_date

while current_date <= end_date:
    dates.append(current_date)
    current_date += timedelta(days=1)

for date in dates:
    print(date.strftime('%Y-%m-%d'))

2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10
2023-02-11
2023-02-12
2023-02-13
2023-02-14
2023-02-15
2023-02-16
2023-02-17
2023-02-18
2023-02-19
2023-02-20
2023-02-21
2023-02-22
2023-02-23
2023-02-24
2023-02-25
2023-02-26
2023-02-27
2023-02-28
2023-03-01


In [20]:
#Question 10
import pandas as pd
dict = {'Brand':['Maruti','Renault','Hyundai'], 'Sales':[250,200,240]}
df= pd.DataFrame(dict)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
